version: "1"
services:
  jenkinks:
    image: jenkins/docker
    build:
      context: .
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins
    privileged: true
    user: root
    volumes:
     - jenkins_home:/var/jenkins_home
     - jenkins_docker_sock:/var/run/docker.sock
  sonarqube:
    image: sonarqube 
    restart: unless-stopped
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  volumes:
    jenkins_home:
    jenkins_docker_sock:
    postgresql_data:
    sonarqube_bundled-plugins:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_db:
    sonarqube_extensions:
    sonarqube_logs: